SET QUOTED_IDENTIFIER ON;
DROP TABLE IF EXISTS dbo.SKU;
CREATE TABLE dbo.SKU
(
	"ID" INT IDENTITY NOT NULL,
	"Code" AS ('s' + CAST(ID AS VARCHAR(10))),
	"Name" VARCHAR(255) NOT NULL,
	CONSTRAINT PK_SKU PRIMARY KEY("ID"),
	CONSTRAINT UQ_SKU_Code UNIQUE("Code")
);

DROP TABLE IF EXISTS dbo.Family;
CREATE TABLE dbo.Family
(
	"ID" INT IDENTITY NOT NULL,
	"SurName" VARCHAR(255) NULL,
	"BudgetValue" DECIMAL(18, 2) NOT NULL,
	CONSTRAINT PK_Family PRIMARY KEY("ID")
);

DROP TABLE IF EXISTS dbo.Basket;
CREATE TABLE dbo.Basket
(
	"ID" INT IDENTITY NOT NULL,
	"ID_SKU" INT NOT NULL,
	"ID_Family" INT NOT NULL,
	"Quantity" INT NOT NULL,
	"Value" DECIMAL(18, 2) NOT NULL,
	"PurchaseDate" DATE CONSTRAINT DF_Basket_PurchaseDate DEFAULT GETDATE() NOT NULL,
	"DiscountValue" DECIMAL (18, 2),
	CONSTRAINT PK_Basket PRIMARY KEY("ID"),
	CONSTRAINT FK_Basket_SKU FOREIGN KEY("ID_SKU") REFERENCES dbo.SKU("ID"),
	CONSTRAINT FK_Basket_Family FOREIGN KEY("ID_Family") REFERENCES dbo.Family("ID"),
	CONSTRAINT CHK_Basket_Quantity CHECK ("Quantity" >= 0),
	CONSTRAINT CHK_Basket_Value CHECK ("Value" >= 0)
);
